env:
  matrix:
    - PHP_VERSION='5.6' PHP_FPM=false PHP_TAG='5.6'
    - PHP_VERSION='5.6' PHP_FPM=true  PHP_TAG='5.6-fpm'
    - PHP_VERSION='7.0' PHP_FPM=false PHP_TAG='7.0'
    - PHP_VERSION='7.0' PHP_FPM=true  PHP_TAG='7.0-fpm'
build:
  pre_ci:
    - chmod +x ./build.sh && ./build.sh
  pre_ci_boot:
    image_name: mygento/php
    image_tag: $PHP_TAG
    pull: false
  ci:
     - php -v
  post_ci:
    - docker push mygento/php:$PHP_TAG

integrations:
    hub:
      - integrationName: Docker
        type: docker
        agent_only: true
