env:
  matrix:
    - PHP_TAG='7.3-full'
    - PHP_TAG='7.4-full'
    - PHP_TAG='7.2-full'
    - PHP_TAG='7.3-fpm'
    - PHP_TAG='7.4-fpm'
    - PHP_TAG='7.2-fpm'
    - PHP_TAG='7.3'
    - PHP_TAG='7.2'
    - PHP_TAG='7.4'
    - PHP_TAG='7.2-debug'
    - PHP_TAG='7.3-debug'
    - PHP_TAG='7.4-debug'
build:
  pre_ci:
    - apt-get install -qqy curl
    - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    - gpg --keyserver hkp://keys.gnupg.net --recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    - curl -sSL https://get.rvm.io | grep -v __rvm_print_headline | bash -s stable --ruby
    - source /usr/local/rvm/scripts/rvm
    - gem install puppet --no-document
    - rm -fR /etc/puppetlabs/code/modules/image_build
    - git clone --single-branch --branch v2 https://github.com/luckyraul/puppetlabs-image_build.git /etc/puppetlabs/code/modules/image_build
    - puppet docker build --image-name mygento/php:$PHP_TAG --no-show-diff
  ci:
     - docker run --rm mygento/php:$PHP_TAG php -v
     - docker run --rm mygento/php:$PHP_TAG php -m
     - docker run --rm mygento/php:$PHP_TAG php -i
  push:
    - docker push mygento/php:$PHP_TAG
    - docker tag mygento/php:$PHP_TAG luckyraul/php:$PHP_TAG
    - docker push luckyraul/php:$PHP_TAG

integrations:
    hub:
      - integrationName: Docker
        type: docker
        agent_only: true
