env:
  matrix:
    - PHP_TAG='5.6-full'
    - PHP_TAG='7.0-full'
    - PHP_TAG='5.6-fpm'
    - PHP_TAG='7.0-fpm'
    - PHP_TAG='5.6'
    - PHP_TAG='7.0'
    - PHP_TAG='7.1'
    - PHP_TAG='7.1-fpm'
    - PHP_TAG='7.1-full'
build:
  pre_ci:
    - apt-get install -qqy curl
    - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    - curl -L https://get.rvm.io | bash -s stable --ruby
    - source /usr/local/rvm/scripts/rvm
    - gem install puppet --no-ri --no-rdoc
    - puppet module install puppetlabs/image_build
    - sed -ie 's/--show_diff//g' /etc/puppetlabs/code/modules/image_build/templates/Dockerfile.erb
    - puppet docker build --image-name mygento/php:$PHP_TAG
  pre_ci_boot:
    image_name: mygento/php
    image_tag: $PHP_TAG
    pull: false
  ci:
     - php -v
     - php -m
  push:
    - docker push mygento/php:$PHP_TAG

integrations:
    hub:
      - integrationName: Docker
        type: docker
        agent_only: true
