env:
  matrix:
    - PHP_VERSION='5.5' PHP_FPM=false
    - PHP_VERSION='5.5' PHP_FPM=true
    - PHP_VERSION='5.6' PHP_FPM=false
    - PHP_VERSION='5.6' PHP_FPM=true
    - PHP_VERSION='7.0' PHP_FPM=false
    - PHP_VERSION='7.0' PHP_FPM=true
  allow_failures:
    - PHP_VERSION='5.5' PHP_FPM=false
    - PHP_VERSION='5.5' PHP_FPM=true
build:
  pre_ci:
    - chmod +x ./build.sh && ./build.sh
  pre_ci_boot:
    image_name: mygento/php
    image_tag: $PHP_COMB
    pull: false
  ci:
     - php -v
  post_ci:
    - docker push mygento/php:$PHP_COMB
integrations:
    hub:
      - integrationName: Docker
        type: docker
        agent_only: true
