name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '7.3-full'
          - '7.4-full'
          - '7.2-full'
          - '7.3-fpm'
          - '7.4-fpm'
          - '7.2-fpm'
          - '7.3'
          - '7.2'
          - '7.4'
          - '7.3-debug'
          - '7.4-debug'
          - '7.2-debug'
          - '8.0-full'
          - '8.0-fpm'
          - '8.0'
          - '8.0-debug'
    steps:
      - uses: actions/checkout@v2

      - id: install_puppet
        name: Install Puppet
        continue-on-error: true
        run: |
          gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          curl -sSL https://get.rvm.io | bash -s stable
          source /home/runner/.rvm/scripts/rvm
          rvm install ruby-2.7.2
          rvm --default use ruby-2.7.2
          sudo gem install puppet --no-document -v '~> 6.18.0'
          sudo rm -fR /etc/puppetlabs/code/modules/image_build
          sudo git clone --single-branch --branch v2 https://github.com/luckyraul/puppetlabs-image_build.git /etc/puppetlabs/code/modules/image_build

      - name: Build Image
        run: sudo puppet docker build --image-name mygento/php:${{ matrix.version }} --no-show-diff
      - name: Test Image Version
        run: docker run --rm mygento/php:${{ matrix.version }} php -v
      - name: Test Image Modules
        run: docker run --rm mygento/php:${{ matrix.version }} php -m
      - name: Test Image Config
        run: docker run --rm mygento/php:${{ matrix.version }} php -i

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image
        run: |
          export IMAGE_NAME=mygento/php:${{ matrix.version }}
          export IMAGE_ID=ghcr.io/luckyraul/php:${{ matrix.version }}

          # Change all uppercase to lowercase
          export IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo $IMAGE_ID

          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
      - name: Push image Mygento
        run: |
          export IMAGE_NAME=mygento/php:${{ matrix.version }}
          export IMAGE_ID=ghcr.io/mygento/php:${{ matrix.version }}

          # Change all uppercase to lowercase
          export IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo $IMAGE_ID

          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
